### ISSUE TITLE
Error pages rendered incorrectly

### ISSUE THREAD

**Issue by imbachb** [oviva-ag/ehealthid-relying-party#58]
When a response returns an error status code the page is rendered incorrectly. The html is shown raw, as if it were escaped.
Following page is currently shown when navigating to the `/auth` route without any of the necessary query parameters:

![image](https://github.com/oviva-ag/ehealthid-relying-party/assets/13905978/62e1835d-a0fe-4845-b751-95a1c2013cf1)
Changing the status code from `400` to `200` in the code returns following page:

![image](https://github.com/oviva-ag/ehealthid-relying-party/assets/13905978/39fff557-ac86-4b9a-a9b7-42ba0de504f0)

It seems that depending on the returned status code the renderer uses either a different error page template that wraps the raw html, or that some sanitation is applied.

I found following issue https://github.com/thomasdarimont/embedded-spring-boot-keycloak-server/issues/14 but I'm not sure if it is related.

**Comment by thomasrichner-oviva** [comment]
Hey @imbachb thanks for the report! Do you happen to have a full HTTP exchange for that recorded?
I think I've seen that before and thought we fixed it.
Maybe not :/

**Comment by imbachb** [comment]
Thanks for looking into it!
Does this help? I currently have a container deployed on https://gid.cloud.acti-on.ch 
Error (when navigating to https://gid.cloud.acti-on.ch/auth)
![image](https://github.com/oviva-ag/ehealthid-relying-party/assets/13905978/9c225e4d-b7df-4d75-8a2b-39d9e7bd2d46)
![image](https://github.com/oviva-ag/ehealthid-relying-party/assets/13905978/3c057160-1490-4862-9778-decb331a46a1)

Ok (when correctly being redirected to https://gid.cloud.acti-on.ch/auth?scope=openid)
![image](https://github.com/oviva-ag/ehealthid-relying-party/assets/13905978/c2ce2899-5849-41c6-8896-450a3b6b93fd)
![image](https://github.com/oviva-ag/ehealthid-relying-party/assets/13905978/6d88c5bf-e067-42a9-a4b1-f1422bd7031c)

**Comment by thomasrichner-oviva** [comment]
Should suffice, let me check.

**Comment by thomasrichner-oviva** [comment]
Ok, I think I've tracked it down to https://github.com/resteasy/resteasy/blob/main/resteasy-core/src/main/java/org/jboss/resteasy/plugins/interceptors/MessageSanitizerContainerResponseFilter.java#L33 . It seems resteasy is a bit too eager with escaping HTML.

**Comment by thomasrichner-oviva** [comment]
internal reference https://oviva-ag.atlassian.net/browse/EPA-102

**Comment by thomasrichner-oviva** [comment]
@imbachb fixed in release https://github.com/oviva-ag/ehealthid-relying-party/releases/tag/ehealthid-relying-party%2Fv0.9.8-rc.0 
Can you give it a try?

**Comment by imbachb** [comment]
Yes, just updated and it works now, amazing. Thank you!
