### ISSUE TITLE
FederationConfig Allowed Redirect URls

### ISSUE THREAD

**Issue by henryallsuch** [oviva-ag/ehealthid-relying-party#85]
Should the redirect call back uri's be coming from `EHEALTHID_RP_REDIRECT_URIS` in the docker environment variable?

Seeing only:

```
"redirect_uris": [
        "/auth/callback"
      ],
 ```     
In the `myrelayexample.com/.well-known/openid-federation` statement.

https://github.com/oviva-ag/ehealthid-relying-party/blob/main/ehealthid-rp/src/main/java/com/oviva/ehealthid/relyingparty/ConfigReader.java#L96

```
...
.scopes(getScopes())
.redirectUris(List.of(baseUri.resolve("/auth/callback").toString()))
.build();
...
````

**Comment by henryallsuch** [comment]
@ McLeanAdam

**Comment by thomasrichner-oviva** [comment]
That is correct, the one in the config is on the oidc side. The one above is for the federation.

**Comment by thomasrichner-oviva** [comment]
Check maybe this diagram to get an idea where which redirect ist: https://github.com/oviva-ag/ehealthid-relying-party?tab=readme-ov-file#authentication-flow-between-all-involved-parties

There are quite a few :)
