### ISSUE TITLE
could not able to find parent pom with artifact id ehealthid-parent

### ISSUE THREAD

**Issue by MANUVILAKUNNATHU** [oviva-ag/ehealthid-relying-party#89]
see the below error when execute goal for install
[[1;31mERROR[m] Failed to execute goal on project [36mehealthid-rp[m: [1;31mCould not resolve dependencies for project com.oviva.ehealthid:ehealthid-rp:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at com.oviva.ehealthid:ehealthid:jar:0.0.1-SNAPSHOT[m: Failed to read artifact descriptor for com.oviva.ehealthid:ehealthid:jar:0.0.1-SNAPSHOT: com.oviva.ehealthid:ehealthid-parent:pom:0.0.1-SNAPSHOT was not found in https://maven.pkg.github.com/oviva-ag/REPOSITORY during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of github has elapsed or updates are forced -> [1m[Help 1][m

please help on this,Thanks

**Comment by thomasrichner-oviva** [comment]
Have you tried `mvn clean install` in the root of the project?
Looks like you are struggling with the basics of Maven.

**Comment by MANUVILAKUNNATHU** [comment]
> Have you tried `mvn clean install` in the root of the project? Looks like you are struggling with the basics of Maven.

Yes we were able to fix the issue .Thanks for your support
