### ISSUE TITLE
Working IDP url for testing AuthenticationFlowExampleTest

### ISSUE THREAD

**Issue by sureshcankado** [oviva-ag/ehealthid-relying-party#92]
Hello Thomas, 

for the testing of https://github.com/oviva-ag/ehealthid-relying-party/blob/main/ehealthid/src/test/java/com/oviva/ehealthid/auth/AuthenticationFlowExampleTest.java

can you provide a working url for this
 var self = URI.create("https://idp-test.oviva.io/auth/realms/master/ehealthid");

**Comment by thomasrichner-oviva** [comment]
This is up to you to provide that: https://wiki.gematik.de/pages/viewpage.action?pageId=544316583
